# -*- coding: utf-8 -*-
#  ***** BEGIN LICENSE BLOCK *****
#  Version: MPL 1.1/GPL 2.0/LGPL 2.1
#  
#  The contents of this file are subject to the Mozilla Public License Version 
#  1.1 (the "License"); you may not use this file except in compliance with 
#  the License. You may obtain a copy of the License at 
#  http://www.mozilla.org/MPL/
#  
#  Software distributed under the License is distributed on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
#  for the specific language governing rights and limitations under the
#  License.
#  
#  The Original Code is the Public Suffix List.
#  
#  The Initial Developer of the Original Code is
#  Jo Hermans <jo.hermans@gmail.com>.
#  Portions created by the Initial Developer are Copyright (C) 2007
#  the Initial Developer. All Rights Reserved.
#  
#  Contributor(s):
#    Ruben Arakelyan <ruben@wackomenace.co.uk>
#    Gervase Markham <gerv@gerv.net>
#    Pamela Greene <pamg.bugs@gmail.com>
#    David Triendl <david@triendl.name>
#    Jothan Frakes <jothan@gmail.com>
#    The kind representatives of many TLD registries
#  
#  Alternatively, the contents of this file may be used under the terms of
#  either the GNU General Public License Version 2 or later (the "GPL"), or
#  the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
#  in which case the provisions of the GPL or the LGPL are applicable instead
#  of those above. If you wish to allow use of your version of this file only
#  under the terms of either the GPL or the LGPL, and not to allow others to
#  use your version of this file under the terms of the MPL, indicate your
#  decision by deleting the provisions above and replace them with the notice
#  and other provisions required by the GPL or the LGPL. If you do not delete
#  the provisions above, a recipient may use your version of this file under
#  the terms of any one of the MPL, the GPL or the LGPL.
#  
#  ***** END LICENSE BLOCK *****

tldTree = {u'ac' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {}},
u'ad' : {u'nom' : {}},
u'ae' : {u'ac' : {},
u'co' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {},
u'sch' : {}},
u'aero' : {u'accident-investigation' : {},
u'accident-prevention' : {},
u'aerobatic' : {},
u'aeroclub' : {},
u'aerodrome' : {},
u'agents' : {},
u'air-surveillance' : {},
u'air-traffic-control' : {},
u'aircraft' : {},
u'airline' : {},
u'airport' : {},
u'airtraffic' : {},
u'ambulance' : {},
u'amusement' : {},
u'association' : {},
u'author' : {},
u'ballooning' : {},
u'broker' : {},
u'caa' : {},
u'cargo' : {},
u'catering' : {},
u'certification' : {},
u'championship' : {},
u'charter' : {},
u'civilaviation' : {},
u'club' : {},
u'conference' : {},
u'consultant' : {},
u'consulting' : {},
u'control' : {},
u'council' : {},
u'crew' : {},
u'design' : {},
u'dgca' : {},
u'educator' : {},
u'emergency' : {},
u'engine' : {},
u'engineer' : {},
u'entertainment' : {},
u'equipment' : {},
u'exchange' : {},
u'express' : {},
u'federation' : {},
u'flight' : {},
u'freight' : {},
u'fuel' : {},
u'gliding' : {},
u'government' : {},
u'groundhandling' : {},
u'group' : {},
u'hanggliding' : {},
u'homebuilt' : {},
u'insurance' : {},
u'journal' : {},
u'journalist' : {},
u'leasing' : {},
u'logistics' : {},
u'magazine' : {},
u'maintenance' : {},
u'marketplace' : {},
u'media' : {},
u'microlight' : {},
u'modelling' : {},
u'navigation' : {},
u'parachuting' : {},
u'paragliding' : {},
u'passenger-association' : {},
u'pilot' : {},
u'press' : {},
u'production' : {},
u'recreation' : {},
u'repbody' : {},
u'res' : {},
u'research' : {},
u'rotorcraft' : {},
u'safety' : {},
u'scientist' : {},
u'services' : {},
u'show' : {},
u'skydiving' : {},
u'software' : {},
u'student' : {},
u'taxi' : {},
u'trader' : {},
u'trading' : {},
u'trainer' : {},
u'union' : {},
u'workinggroup' : {},
u'works' : {}},
u'af' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'ag' : {u'co' : {},
u'com' : {},
u'net' : {},
u'nom' : {},
u'org' : {}},
u'ai' : {u'com' : {},
u'net' : {},
u'off' : {},
u'org' : {}},
u'al' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {}},
u'am' : {},
u'an' : {u'com' : {},
u'edu' : {},
u'net' : {},
u'org' : {}},
u'ao' : {u'co' : {},
u'ed' : {},
u'gv' : {},
u'it' : {},
u'og' : {},
u'pb' : {}},
u'aq' : {},
u'ar' : {u'*' : {},
u'congresodelalengua3' : {u'!' : {}},
u'educ' : {u'!' : {}},
u'gobiernoelectronico' : {u'!' : {}},
u'mecon' : {u'!' : {}},
u'nacion' : {u'!' : {}},
u'nic' : {u'!' : {}},
u'promocion' : {u'!' : {}},
u'retina' : {u'!' : {}},
u'uba' : {u'!' : {}}},
u'arpa' : {u'e164' : {},
u'in-addr' : {},
u'ip6' : {},
u'iris' : {},
u'uri' : {},
u'urn' : {}},
u'as' : {u'gov' : {}},
u'asia' : {},
u'at' : {u'ac' : {},
u'biz' : {},
u'co' : {},
u'gv' : {},
u'info' : {},
u'or' : {},
u'priv' : {}},
u'au' : {u'*' : {},
u'act' : {},
u'edu' : {u'act' : {},
u'nsw' : {},
u'nt' : {},
u'qld' : {},
u'sa' : {},
u'tas' : {},
u'vic' : {},
u'wa' : {}},
u'gov' : {u'act' : {},
u'nt' : {},
u'qld' : {},
u'sa' : {},
u'tas' : {},
u'vic' : {},
u'wa' : {}},
u'nsw' : {},
u'nt' : {},
u'qld' : {},
u'sa' : {},
u'tas' : {},
u'vic' : {},
u'wa' : {}},
u'aw' : {u'com' : {}},
u'ax' : {},
u'az' : {u'biz' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'info' : {},
u'int' : {},
u'mil' : {},
u'name' : {},
u'net' : {},
u'org' : {},
u'pp' : {},
u'pro' : {}},
u'ba' : {u'co' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {},
u'rs' : {},
u'unbi' : {},
u'unsa' : {}},
u'bb' : {u'biz' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'info' : {},
u'net' : {},
u'org' : {},
u'store' : {}},
u'bd' : {u'*' : {}},
u'be' : {u'ac' : {}},
u'bf' : {u'gov' : {}},
u'bg' : {u'0' : {},
u'1' : {},
u'2' : {},
u'3' : {},
u'4' : {},
u'5' : {},
u'6' : {},
u'7' : {},
u'8' : {},
u'9' : {},
u'a' : {},
u'b' : {},
u'c' : {},
u'd' : {},
u'e' : {},
u'f' : {},
u'g' : {},
u'h' : {},
u'i' : {},
u'j' : {},
u'k' : {},
u'l' : {},
u'm' : {},
u'n' : {},
u'o' : {},
u'p' : {},
u'q' : {},
u'r' : {},
u's' : {},
u't' : {},
u'u' : {},
u'v' : {},
u'w' : {},
u'x' : {},
u'y' : {},
u'z' : {}},
u'bh' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'bi' : {u'co' : {},
u'com' : {},
u'edu' : {},
u'or' : {},
u'org' : {}},
u'biz' : {},
u'bj' : {u'asso' : {},
u'barreau' : {},
u'gouv' : {}},
u'bm' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'bn' : {u'*' : {}},
u'bo' : {u'com' : {},
u'edu' : {},
u'gob' : {},
u'gov' : {},
u'int' : {},
u'mil' : {},
u'net' : {},
u'org' : {},
u'tv' : {}},
u'br' : {u'adm' : {},
u'adv' : {},
u'agr' : {},
u'am' : {},
u'arq' : {},
u'art' : {},
u'ato' : {},
u'bio' : {},
u'blog' : {},
u'bmd' : {},
u'can' : {},
u'cim' : {},
u'cng' : {},
u'cnt' : {},
u'com' : {},
u'coop' : {},
u'ecn' : {},
u'edu' : {},
u'eng' : {},
u'esp' : {},
u'etc' : {},
u'eti' : {},
u'far' : {},
u'flog' : {},
u'fm' : {},
u'fnd' : {},
u'fot' : {},
u'fst' : {},
u'g12' : {},
u'ggf' : {},
u'gov' : {},
u'imb' : {},
u'ind' : {},
u'inf' : {},
u'jor' : {},
u'jus' : {},
u'lel' : {},
u'mat' : {},
u'med' : {},
u'mil' : {},
u'mus' : {},
u'net' : {},
u'nom' : {},
u'not' : {},
u'ntr' : {},
u'odo' : {},
u'org' : {},
u'ppg' : {},
u'pro' : {},
u'psc' : {},
u'psi' : {},
u'qsl' : {},
u'rec' : {},
u'slg' : {},
u'srv' : {},
u'tmp' : {},
u'trd' : {},
u'tur' : {},
u'tv' : {},
u'vet' : {},
u'vlog' : {},
u'wiki' : {},
u'zlg' : {}},
u'bs' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'bt' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'bw' : {u'co' : {},
u'org' : {}},
u'by' : {u'com' : {},
u'gov' : {},
u'mil' : {},
u'of' : {}},
u'bz' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'ca' : {u'ab' : {},
u'bc' : {},
u'gc' : {},
u'mb' : {},
u'nb' : {},
u'nf' : {},
u'nl' : {},
u'ns' : {},
u'nt' : {},
u'nu' : {},
u'on' : {},
u'pe' : {},
u'qc' : {},
u'sk' : {},
u'yk' : {}},
u'cat' : {},
u'cc' : {},
u'cd' : {u'gov' : {}},
u'cf' : {},
u'cg' : {},
u'ch' : {},
u'ci' : {u'ac' : {},
u'asso' : {},
u'aéroport' : {},
u'co' : {},
u'com' : {},
u'ed' : {},
u'edu' : {},
u'go' : {},
u'gouv' : {},
u'int' : {},
u'md' : {},
u'net' : {},
u'or' : {},
u'org' : {},
u'presse' : {}},
u'ck' : {u'*' : {}},
u'cl' : {u'gob' : {},
u'gov' : {}},
u'cm' : {u'gov' : {}},
u'cn' : {u'ac' : {},
u'ah' : {},
u'bj' : {},
u'com' : {},
u'cq' : {},
u'edu' : {},
u'fj' : {},
u'gd' : {},
u'gov' : {},
u'gs' : {},
u'gx' : {},
u'gz' : {},
u'ha' : {},
u'hb' : {},
u'he' : {},
u'hi' : {},
u'hk' : {},
u'hl' : {},
u'hn' : {},
u'jl' : {},
u'js' : {},
u'jx' : {},
u'ln' : {},
u'mil' : {},
u'mo' : {},
u'net' : {},
u'nm' : {},
u'nx' : {},
u'org' : {},
u'qh' : {},
u'sc' : {},
u'sd' : {},
u'sh' : {},
u'sn' : {},
u'sx' : {},
u'tj' : {},
u'tw' : {},
u'xj' : {},
u'xz' : {},
u'yn' : {},
u'zj' : {},
u'公司' : {},
u'網絡' : {},
u'网络' : {}},
u'co' : {u'arts' : {},
u'com' : {},
u'edu' : {},
u'firm' : {},
u'gov' : {},
u'info' : {},
u'int' : {},
u'mil' : {},
u'net' : {},
u'nom' : {},
u'org' : {},
u'rec' : {},
u'web' : {}},
u'com' : {u'appspot' : {},
u'ar' : {},
u'br' : {},
u'cn' : {},
u'de' : {},
u'eu' : {},
u'gb' : {},
u'hu' : {},
u'jpn' : {},
u'kr' : {},
u'no' : {},
u'operaunite' : {},
u'qc' : {},
u'ru' : {},
u'sa' : {},
u'se' : {},
u'uk' : {},
u'us' : {},
u'uy' : {},
u'za' : {}},
u'coop' : {},
u'cr' : {u'ac' : {},
u'co' : {},
u'ed' : {},
u'fi' : {},
u'go' : {},
u'or' : {},
u'sa' : {}},
u'cu' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'inf' : {},
u'net' : {},
u'org' : {}},
u'cv' : {},
u'cx' : {u'gov' : {}},
u'cy' : {u'*' : {}},
u'cz' : {},
u'de' : {},
u'dj' : {},
u'dk' : {},
u'dm' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'do' : {u'*' : {}},
u'dz' : {u'art' : {},
u'asso' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {},
u'pol' : {}},
u'ec' : {u'com' : {},
u'edu' : {},
u'fin' : {},
u'gov' : {},
u'info' : {},
u'k12' : {},
u'med' : {},
u'mil' : {},
u'net' : {},
u'org' : {},
u'pro' : {}},
u'edu' : {},
u'ee' : {u'aip' : {},
u'com' : {},
u'edu' : {},
u'fie' : {},
u'gov' : {},
u'lib' : {},
u'med' : {},
u'org' : {},
u'pri' : {},
u'riik' : {}},
u'eg' : {u'*' : {}},
u'er' : {u'*' : {}},
u'es' : {u'com' : {},
u'edu' : {},
u'gob' : {},
u'nom' : {},
u'org' : {}},
u'et' : {u'*' : {}},
u'eu' : {},
u'fi' : {u'aland' : {},
u'iki' : {}},
u'fj' : {u'*' : {}},
u'fk' : {u'*' : {}},
u'fm' : {},
u'fo' : {},
u'fr' : {u'aeroport' : {},
u'assedic' : {},
u'asso' : {},
u'avocat' : {},
u'avoues' : {},
u'cci' : {},
u'chambagri' : {},
u'chirurgiens-dentistes' : {},
u'com' : {},
u'experts-comptables' : {},
u'geometre-expert' : {},
u'gouv' : {},
u'greta' : {},
u'huissier-justice' : {},
u'medecin' : {},
u'nom' : {},
u'notaires' : {},
u'pharmacien' : {},
u'port' : {},
u'prd' : {},
u'presse' : {},
u'tm' : {},
u'veterinaire' : {}},
u'ga' : {},
u'gd' : {},
u'ge' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {},
u'pvt' : {}},
u'gf' : {},
u'gg' : {u'co' : {},
u'gov' : {},
u'net' : {},
u'org' : {},
u'sch' : {}},
u'gh' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'org' : {}},
u'gi' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'ltd' : {},
u'mod' : {},
u'org' : {}},
u'gl' : {},
u'gm' : {},
u'gn' : {u'ac' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'gov' : {},
u'gp' : {u'asso' : {},
u'com' : {},
u'edu' : {},
u'mobi' : {},
u'net' : {},
u'org' : {}},
u'gq' : {},
u'gr' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'gs' : {},
u'gt' : {u'*' : {}},
u'gu' : {u'*' : {}},
u'gw' : {},
u'gy' : {u'co' : {},
u'com' : {},
u'net' : {}},
u'hk' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'idv' : {},
u'net' : {},
u'org' : {},
u'个人' : {},
u'個人' : {},
u'公司' : {},
u'政府' : {},
u'敎育' : {},
u'教育' : {},
u'箇人' : {},
u'組織' : {},
u'組织' : {},
u'網絡' : {},
u'網络' : {},
u'组織' : {},
u'组织' : {},
u'网絡' : {},
u'网络' : {}},
u'hm' : {},
u'hn' : {u'com' : {},
u'edu' : {},
u'gob' : {},
u'mil' : {},
u'net' : {},
u'org' : {}},
u'hr' : {u'com' : {},
u'from' : {},
u'iz' : {},
u'name' : {}},
u'ht' : {u'adult' : {},
u'art' : {},
u'asso' : {},
u'com' : {},
u'coop' : {},
u'edu' : {},
u'firm' : {},
u'gouv' : {},
u'info' : {},
u'med' : {},
u'net' : {},
u'org' : {},
u'perso' : {},
u'pol' : {},
u'pro' : {},
u'rel' : {},
u'shop' : {}},
u'hu' : {u'2000' : {},
u'agrar' : {},
u'bolt' : {},
u'casino' : {},
u'city' : {},
u'co' : {},
u'erotica' : {},
u'erotika' : {},
u'film' : {},
u'forum' : {},
u'games' : {},
u'hotel' : {},
u'info' : {},
u'ingatlan' : {},
u'jogasz' : {},
u'konyvelo' : {},
u'lakas' : {},
u'media' : {},
u'news' : {},
u'org' : {},
u'priv' : {},
u'reklam' : {},
u'sex' : {},
u'shop' : {},
u'sport' : {},
u'suli' : {},
u'szex' : {},
u'tm' : {},
u'tozsde' : {},
u'utazas' : {},
u'video' : {}},
u'id' : {u'ac' : {},
u'co' : {},
u'go' : {},
u'mil' : {},
u'net' : {},
u'or' : {},
u'sch' : {},
u'web' : {}},
u'ie' : {u'gov' : {}},
u'il' : {u'*' : {}},
u'im' : {u'ac' : {},
u'co' : {u'ltd' : {},
u'plc' : {}},
u'gov' : {},
u'net' : {},
u'nic' : {},
u'org' : {}},
u'in' : {u'ac' : {},
u'co' : {},
u'edu' : {},
u'firm' : {},
u'gen' : {},
u'gov' : {},
u'ind' : {},
u'mil' : {},
u'net' : {},
u'nic' : {},
u'org' : {},
u'res' : {}},
u'info' : {},
u'int' : {u'eu' : {}},
u'io' : {u'com' : {}},
u'iq' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {}},
u'ir' : {u'ac' : {},
u'co' : {},
u'gov' : {},
u'id' : {},
u'net' : {},
u'org' : {},
u'sch' : {},
u'ايران' : {},
u'ایران' : {}},
u'is' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'int' : {},
u'net' : {},
u'org' : {}},
u'it' : {u'ag' : {},
u'agrigento' : {},
u'al' : {},
u'alessandria' : {},
u'alto-adige' : {},
u'altoadige' : {},
u'an' : {},
u'ancona' : {},
u'andria-barletta-trani' : {},
u'andria-trani-barletta' : {},
u'andriabarlettatrani' : {},
u'andriatranibarletta' : {},
u'ao' : {},
u'aosta' : {},
u'aoste' : {},
u'ap' : {},
u'aq' : {},
u'aquila' : {},
u'ar' : {},
u'arezzo' : {},
u'ascoli-piceno' : {},
u'ascolipiceno' : {},
u'asti' : {},
u'at' : {},
u'av' : {},
u'avellino' : {},
u'ba' : {},
u'balsan' : {},
u'bari' : {},
u'barletta-trani-andria' : {},
u'barlettatraniandria' : {},
u'belluno' : {},
u'benevento' : {},
u'bergamo' : {},
u'bg' : {},
u'bi' : {},
u'biella' : {},
u'bl' : {},
u'bn' : {},
u'bo' : {},
u'bologna' : {},
u'bolzano' : {},
u'bozen' : {},
u'br' : {},
u'brescia' : {},
u'brindisi' : {},
u'bs' : {},
u'bt' : {},
u'bz' : {},
u'ca' : {},
u'cagliari' : {},
u'caltanissetta' : {},
u'campidano-medio' : {},
u'campidanomedio' : {},
u'campobasso' : {},
u'carbonia-iglesias' : {},
u'carboniaiglesias' : {},
u'carrara-massa' : {},
u'carraramassa' : {},
u'caserta' : {},
u'catania' : {},
u'catanzaro' : {},
u'cb' : {},
u'ce' : {},
u'cesena-forli' : {},
u'cesenaforli' : {},
u'ch' : {},
u'chieti' : {},
u'ci' : {},
u'cl' : {},
u'cn' : {},
u'co' : {},
u'como' : {},
u'cosenza' : {},
u'cr' : {},
u'cremona' : {},
u'crotone' : {},
u'cs' : {},
u'ct' : {},
u'cuneo' : {},
u'cz' : {},
u'dell-ogliastra' : {},
u'dellogliastra' : {},
u'edu' : {},
u'en' : {},
u'enna' : {},
u'fc' : {},
u'fe' : {},
u'fermo' : {},
u'ferrara' : {},
u'fg' : {},
u'fi' : {},
u'firenze' : {},
u'florence' : {},
u'fm' : {},
u'foggia' : {},
u'forli-cesena' : {},
u'forlicesena' : {},
u'fr' : {},
u'frosinone' : {},
u'ge' : {},
u'genoa' : {},
u'genova' : {},
u'go' : {},
u'gorizia' : {},
u'gov' : {},
u'gr' : {},
u'grosseto' : {},
u'iglesias-carbonia' : {},
u'iglesiascarbonia' : {},
u'im' : {},
u'imperia' : {},
u'is' : {},
u'isernia' : {},
u'kr' : {},
u'la-spezia' : {},
u'laquila' : {},
u'laspezia' : {},
u'latina' : {},
u'lc' : {},
u'le' : {},
u'lecce' : {},
u'lecco' : {},
u'li' : {},
u'livorno' : {},
u'lo' : {},
u'lodi' : {},
u'lt' : {},
u'lu' : {},
u'lucca' : {},
u'macerata' : {},
u'mantova' : {},
u'massa-carrara' : {},
u'massacarrara' : {},
u'matera' : {},
u'mb' : {},
u'mc' : {},
u'me' : {},
u'medio-campidano' : {},
u'mediocampidano' : {},
u'messina' : {},
u'mi' : {},
u'milan' : {},
u'milano' : {},
u'mn' : {},
u'mo' : {},
u'modena' : {},
u'monza' : {},
u'monza-brianza' : {},
u'monza-e-della-brianza' : {},
u'monzabrianza' : {},
u'monzaebrianza' : {},
u'monzaedellabrianza' : {},
u'ms' : {},
u'mt' : {},
u'na' : {},
u'naples' : {},
u'napoli' : {},
u'no' : {},
u'novara' : {},
u'nu' : {},
u'nuoro' : {},
u'og' : {},
u'ogliastra' : {},
u'olbia-tempio' : {},
u'olbiatempio' : {},
u'or' : {},
u'oristano' : {},
u'ot' : {},
u'pa' : {},
u'padova' : {},
u'padua' : {},
u'palermo' : {},
u'parma' : {},
u'pavia' : {},
u'pc' : {},
u'pd' : {},
u'pe' : {},
u'perugia' : {},
u'pesaro-urbino' : {},
u'pesarourbino' : {},
u'pescara' : {},
u'pg' : {},
u'pi' : {},
u'piacenza' : {},
u'pisa' : {},
u'pistoia' : {},
u'pn' : {},
u'po' : {},
u'pordenone' : {},
u'potenza' : {},
u'pr' : {},
u'prato' : {},
u'pt' : {},
u'pu' : {},
u'pv' : {},
u'pz' : {},
u'ra' : {},
u'ragusa' : {},
u'ravenna' : {},
u'rc' : {},
u're' : {},
u'reggio-calabria' : {},
u'reggio-emilia' : {},
u'reggiocalabria' : {},
u'reggioemilia' : {},
u'rg' : {},
u'ri' : {},
u'rieti' : {},
u'rimini' : {},
u'rm' : {},
u'rn' : {},
u'ro' : {},
u'roma' : {},
u'rome' : {},
u'rovigo' : {},
u'sa' : {},
u'salerno' : {},
u'sassari' : {},
u'savona' : {},
u'si' : {},
u'siena' : {},
u'siracusa' : {},
u'so' : {},
u'sondrio' : {},
u'sp' : {},
u'sr' : {},
u'ss' : {},
u'suedtirol' : {},
u'sv' : {},
u'ta' : {},
u'taranto' : {},
u'te' : {},
u'tempio-olbia' : {},
u'tempioolbia' : {},
u'teramo' : {},
u'terni' : {},
u'tn' : {},
u'to' : {},
u'torino' : {},
u'tp' : {},
u'tr' : {},
u'trani-andria-barletta' : {},
u'trani-barletta-andria' : {},
u'traniandriabarletta' : {},
u'tranibarlettaandria' : {},
u'trapani' : {},
u'trentino' : {},
u'trento' : {},
u'treviso' : {},
u'trieste' : {},
u'ts' : {},
u'turin' : {},
u'tv' : {},
u'ud' : {},
u'udine' : {},
u'urbino-pesaro' : {},
u'urbinopesaro' : {},
u'va' : {},
u'varese' : {},
u'vb' : {},
u'vc' : {},
u've' : {},
u'venezia' : {},
u'venice' : {},
u'verbania' : {},
u'vercelli' : {},
u'verona' : {},
u'vi' : {},
u'vibo-valentia' : {},
u'vibovalentia' : {},
u'vicenza' : {},
u'viterbo' : {},
u'vr' : {},
u'vs' : {},
u'vt' : {},
u'vv' : {}},
u'je' : {u'co' : {},
u'gov' : {},
u'net' : {},
u'org' : {},
u'sch' : {}},
u'jm' : {u'*' : {}},
u'jo' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'name' : {},
u'net' : {},
u'org' : {},
u'sch' : {}},
u'jobs' : {},
u'jp' : {u'ac' : {},
u'ad' : {},
u'aichi' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'akita' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'aomori' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'chiba' : {u'*' : {},
u'city' : {u'!' : {}},
u'pref' : {u'!' : {}}},
u'co' : {},
u'ed' : {},
u'ehime' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'fukui' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'fukuoka' : {u'*' : {},
u'city' : {u'!' : {}},
u'pref' : {u'!' : {}}},
u'fukushima' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'gifu' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'go' : {},
u'gr' : {},
u'gunma' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'hiroshima' : {u'*' : {},
u'city' : {u'!' : {}},
u'pref' : {u'!' : {}}},
u'hokkaido' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'hyogo' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'ibaraki' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'ishikawa' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'iwate' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'kagawa' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'kagoshima' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'kanagawa' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'kawasaki' : {u'*' : {},
u'city' : {u'!' : {}}},
u'kitakyushu' : {u'*' : {},
u'city' : {u'!' : {}}},
u'kobe' : {u'*' : {},
u'city' : {u'!' : {}}},
u'kochi' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'kumamoto' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'kyoto' : {u'*' : {},
u'city' : {u'!' : {}},
u'pref' : {u'!' : {}}},
u'lg' : {},
u'mie' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'miyagi' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'miyazaki' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'nagano' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'nagasaki' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'nagoya' : {u'*' : {},
u'city' : {u'!' : {}}},
u'nara' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'ne' : {},
u'niigata' : {u'*' : {},
u'city' : {u'!' : {}},
u'pref' : {u'!' : {}}},
u'oita' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'okayama' : {u'*' : {},
u'city' : {u'!' : {}},
u'pref' : {u'!' : {}}},
u'okinawa' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'or' : {},
u'osaka' : {u'*' : {},
u'city' : {u'!' : {}},
u'pref' : {u'!' : {}}},
u'saga' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'saitama' : {u'*' : {},
u'city' : {u'!' : {}},
u'pref' : {u'!' : {}}},
u'sapporo' : {u'*' : {},
u'city' : {u'!' : {}}},
u'sendai' : {u'*' : {},
u'city' : {u'!' : {}}},
u'shiga' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'shimane' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'shizuoka' : {u'*' : {},
u'city' : {u'!' : {}},
u'pref' : {u'!' : {}}},
u'tochigi' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'tokushima' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'tokyo' : {u'*' : {},
u'metro' : {u'!' : {}}},
u'tottori' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'toyama' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'wakayama' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'yamagata' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'yamaguchi' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'yamanashi' : {u'*' : {},
u'pref' : {u'!' : {}}},
u'yokohama' : {u'*' : {},
u'city' : {u'!' : {}}}},
u'ke' : {u'*' : {}},
u'kg' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {}},
u'kh' : {u'*' : {}},
u'ki' : {u'biz' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'info' : {},
u'net' : {},
u'org' : {}},
u'km' : {u'ass' : {},
u'asso' : {},
u'com' : {},
u'coop' : {},
u'edu' : {},
u'gouv' : {},
u'gov' : {},
u'medecin' : {},
u'mil' : {},
u'nom' : {},
u'notaires' : {},
u'org' : {},
u'pharmaciens' : {},
u'prd' : {},
u'presse' : {},
u'tm' : {},
u'veterinaire' : {}},
u'kn' : {u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'kp' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'org' : {},
u'rep' : {},
u'tra' : {}},
u'kr' : {u'ac' : {},
u'busan' : {},
u'chungbuk' : {},
u'chungnam' : {},
u'co' : {},
u'daegu' : {},
u'daejeon' : {},
u'es' : {},
u'gangwon' : {},
u'go' : {},
u'gwangju' : {},
u'gyeongbuk' : {},
u'gyeonggi' : {},
u'gyeongnam' : {},
u'hs' : {},
u'incheon' : {},
u'jeju' : {},
u'jeonbuk' : {},
u'jeonnam' : {},
u'kg' : {},
u'mil' : {},
u'ms' : {},
u'ne' : {},
u'or' : {},
u'pe' : {},
u're' : {},
u'sc' : {},
u'seoul' : {},
u'ulsan' : {}},
u'kw' : {u'*' : {}},
u'ky' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'kz' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {}},
u'la' : {u'c' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'info' : {},
u'int' : {},
u'net' : {},
u'org' : {},
u'per' : {}},
u'lb' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'lc' : {u'co' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'li' : {},
u'lk' : {u'assn' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'grp' : {},
u'hotel' : {},
u'int' : {},
u'ltd' : {},
u'net' : {},
u'ngo' : {},
u'org' : {},
u'sch' : {},
u'soc' : {},
u'web' : {}},
u'local' : {},
u'lr' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'ls' : {u'co' : {},
u'org' : {}},
u'lt' : {u'gov' : {}},
u'lu' : {},
u'lv' : {u'asn' : {},
u'com' : {},
u'conf' : {},
u'edu' : {},
u'gov' : {},
u'id' : {},
u'mil' : {},
u'net' : {},
u'org' : {}},
u'ly' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'id' : {},
u'med' : {},
u'net' : {},
u'org' : {},
u'plc' : {},
u'sch' : {}},
u'ma' : {u'ac' : {},
u'co' : {},
u'gov' : {},
u'net' : {},
u'org' : {},
u'press' : {}},
u'mc' : {u'asso' : {},
u'tm' : {}},
u'md' : {},
u'me' : {u'ac' : {},
u'co' : {},
u'edu' : {},
u'gov' : {},
u'its' : {},
u'net' : {},
u'org' : {},
u'priv' : {}},
u'mg' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'nom' : {},
u'org' : {},
u'prd' : {},
u'tm' : {}},
u'mh' : {},
u'mil' : {},
u'mk' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'inf' : {},
u'name' : {},
u'net' : {},
u'org' : {}},
u'ml' : {u'com' : {},
u'edu' : {},
u'gouv' : {},
u'gov' : {},
u'net' : {},
u'org' : {},
u'presse' : {}},
u'mm' : {u'*' : {}},
u'mn' : {u'edu' : {},
u'gov' : {},
u'org' : {}},
u'mo' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'mobi' : {},
u'mp' : {},
u'mq' : {},
u'mr' : {u'gov' : {}},
u'ms' : {},
u'mt' : {u'*' : {}},
u'mu' : {u'ac' : {},
u'co' : {},
u'com' : {},
u'gov' : {},
u'net' : {},
u'or' : {},
u'org' : {}},
u'museum' : {u'academy' : {},
u'agriculture' : {},
u'air' : {},
u'airguard' : {},
u'alabama' : {},
u'alaska' : {},
u'amber' : {},
u'ambulance' : {},
u'american' : {},
u'americana' : {},
u'americanantiques' : {},
u'americanart' : {},
u'amsterdam' : {},
u'and' : {},
u'annefrank' : {},
u'anthro' : {},
u'anthropology' : {},
u'antiques' : {},
u'aquarium' : {},
u'arboretum' : {},
u'archaeological' : {},
u'archaeology' : {},
u'architecture' : {},
u'art' : {},
u'artanddesign' : {},
u'artcenter' : {},
u'artdeco' : {},
u'arteducation' : {},
u'artgallery' : {},
u'arts' : {},
u'artsandcrafts' : {},
u'asmatart' : {},
u'assassination' : {},
u'assisi' : {},
u'association' : {},
u'astronomy' : {},
u'atlanta' : {},
u'austin' : {},
u'australia' : {},
u'automotive' : {},
u'aviation' : {},
u'axis' : {},
u'badajoz' : {},
u'baghdad' : {},
u'bahn' : {},
u'bale' : {},
u'baltimore' : {},
u'barcelona' : {},
u'baseball' : {},
u'basel' : {},
u'baths' : {},
u'bauern' : {},
u'beauxarts' : {},
u'beeldengeluid' : {},
u'bellevue' : {},
u'bergbau' : {},
u'berkeley' : {},
u'berlin' : {},
u'bern' : {},
u'bible' : {},
u'bilbao' : {},
u'bill' : {},
u'birdart' : {},
u'birthplace' : {},
u'bonn' : {},
u'boston' : {},
u'botanical' : {},
u'botanicalgarden' : {},
u'botanicgarden' : {},
u'botany' : {},
u'brandywinevalley' : {},
u'brasil' : {},
u'bristol' : {},
u'british' : {},
u'britishcolumbia' : {},
u'broadcast' : {},
u'brunel' : {},
u'brussel' : {},
u'brussels' : {},
u'bruxelles' : {},
u'building' : {},
u'burghof' : {},
u'bus' : {},
u'bushey' : {},
u'cadaques' : {},
u'california' : {},
u'cambridge' : {},
u'can' : {},
u'canada' : {},
u'capebreton' : {},
u'carrier' : {},
u'cartoonart' : {},
u'casadelamoneda' : {},
u'castle' : {},
u'castres' : {},
u'celtic' : {},
u'center' : {},
u'chattanooga' : {},
u'cheltenham' : {},
u'chesapeakebay' : {},
u'chicago' : {},
u'children' : {},
u'childrens' : {},
u'childrensgarden' : {},
u'chiropractic' : {},
u'chocolate' : {},
u'christiansburg' : {},
u'cincinnati' : {},
u'cinema' : {},
u'circus' : {},
u'civilisation' : {},
u'civilization' : {},
u'civilwar' : {},
u'clinton' : {},
u'clock' : {},
u'coal' : {},
u'coastaldefence' : {},
u'cody' : {},
u'coldwar' : {},
u'collection' : {},
u'colonialwilliamsburg' : {},
u'coloradoplateau' : {},
u'columbia' : {},
u'columbus' : {},
u'communication' : {},
u'communications' : {},
u'community' : {},
u'computer' : {},
u'computerhistory' : {},
u'comunicações' : {},
u'contemporary' : {},
u'contemporaryart' : {},
u'convent' : {},
u'copenhagen' : {},
u'corporation' : {},
u'correios-e-telecomunicações' : {},
u'corvette' : {},
u'costume' : {},
u'countryestate' : {},
u'county' : {},
u'crafts' : {},
u'cranbrook' : {},
u'creation' : {},
u'cultural' : {},
u'culturalcenter' : {},
u'culture' : {},
u'cyber' : {},
u'cymru' : {},
u'dali' : {},
u'dallas' : {},
u'database' : {},
u'ddr' : {},
u'decorativearts' : {},
u'delaware' : {},
u'delmenhorst' : {},
u'denmark' : {},
u'depot' : {},
u'design' : {},
u'detroit' : {},
u'dinosaur' : {},
u'discovery' : {},
u'dolls' : {},
u'donostia' : {},
u'durham' : {},
u'eastafrica' : {},
u'eastcoast' : {},
u'education' : {},
u'educational' : {},
u'egyptian' : {},
u'eisenbahn' : {},
u'elburg' : {},
u'elvendrell' : {},
u'embroidery' : {},
u'encyclopedic' : {},
u'england' : {},
u'entomology' : {},
u'environment' : {},
u'environmentalconservation' : {},
u'epilepsy' : {},
u'essex' : {},
u'estate' : {},
u'ethnology' : {},
u'exeter' : {},
u'exhibition' : {},
u'family' : {},
u'farm' : {},
u'farmequipment' : {},
u'farmers' : {},
u'farmstead' : {},
u'field' : {},
u'figueres' : {},
u'filatelia' : {},
u'film' : {},
u'fineart' : {},
u'finearts' : {},
u'finland' : {},
u'flanders' : {},
u'florida' : {},
u'force' : {},
u'fortmissoula' : {},
u'fortworth' : {},
u'foundation' : {},
u'francaise' : {},
u'frankfurt' : {},
u'franziskaner' : {},
u'freemasonry' : {},
u'freiburg' : {},
u'fribourg' : {},
u'frog' : {},
u'fundacio' : {},
u'furniture' : {},
u'gallery' : {},
u'garden' : {},
u'gateway' : {},
u'geelvinck' : {},
u'gemological' : {},
u'geology' : {},
u'georgia' : {},
u'giessen' : {},
u'glas' : {},
u'glass' : {},
u'gorge' : {},
u'grandrapids' : {},
u'graz' : {},
u'guernsey' : {},
u'halloffame' : {},
u'hamburg' : {},
u'handson' : {},
u'harvestcelebration' : {},
u'hawaii' : {},
u'health' : {},
u'heimatunduhren' : {},
u'hellas' : {},
u'helsinki' : {},
u'hembygdsforbund' : {},
u'heritage' : {},
u'histoire' : {},
u'historical' : {},
u'historicalsociety' : {},
u'historichouses' : {},
u'historisch' : {},
u'historisches' : {},
u'history' : {},
u'historyofscience' : {},
u'horology' : {},
u'house' : {},
u'humanities' : {},
u'illustration' : {},
u'imageandsound' : {},
u'indian' : {},
u'indiana' : {},
u'indianapolis' : {},
u'indianmarket' : {},
u'intelligence' : {},
u'interactive' : {},
u'iraq' : {},
u'iron' : {},
u'isleofman' : {},
u'jamison' : {},
u'jefferson' : {},
u'jerusalem' : {},
u'jewelry' : {},
u'jewish' : {},
u'jewishart' : {},
u'jfk' : {},
u'journalism' : {},
u'judaica' : {},
u'judygarland' : {},
u'juedisches' : {},
u'juif' : {},
u'karate' : {},
u'karikatur' : {},
u'kids' : {},
u'koebenhavn' : {},
u'koeln' : {},
u'kunst' : {},
u'kunstsammlung' : {},
u'kunstunddesign' : {},
u'labor' : {},
u'labour' : {},
u'lajolla' : {},
u'lancashire' : {},
u'landes' : {},
u'lans' : {},
u'larsson' : {},
u'lewismiller' : {},
u'lincoln' : {},
u'linz' : {},
u'living' : {},
u'livinghistory' : {},
u'localhistory' : {},
u'london' : {},
u'losangeles' : {},
u'louvre' : {},
u'loyalist' : {},
u'lucerne' : {},
u'luxembourg' : {},
u'luzern' : {},
u'läns' : {},
u'mad' : {},
u'madrid' : {},
u'mallorca' : {},
u'manchester' : {},
u'mansion' : {},
u'mansions' : {},
u'manx' : {},
u'marburg' : {},
u'maritime' : {},
u'maritimo' : {},
u'maryland' : {},
u'marylhurst' : {},
u'media' : {},
u'medical' : {},
u'medizinhistorisches' : {},
u'meeres' : {},
u'memorial' : {},
u'mesaverde' : {},
u'michigan' : {},
u'midatlantic' : {},
u'military' : {},
u'mill' : {},
u'miners' : {},
u'mining' : {},
u'minnesota' : {},
u'missile' : {},
u'missoula' : {},
u'modern' : {},
u'moma' : {},
u'money' : {},
u'monmouth' : {},
u'monticello' : {},
u'montreal' : {},
u'moscow' : {},
u'motorcycle' : {},
u'muenchen' : {},
u'muenster' : {},
u'mulhouse' : {},
u'muncie' : {},
u'museet' : {},
u'museumcenter' : {},
u'museumvereniging' : {},
u'music' : {},
u'national' : {},
u'nationalfirearms' : {},
u'nationalheritage' : {},
u'nativeamerican' : {},
u'naturalhistory' : {},
u'naturalhistorymuseum' : {},
u'naturalsciences' : {},
u'nature' : {},
u'naturhistorisches' : {},
u'natuurwetenschappen' : {},
u'naumburg' : {},
u'naval' : {},
u'nebraska' : {},
u'neues' : {},
u'newhampshire' : {},
u'newjersey' : {},
u'newmexico' : {},
u'newport' : {},
u'newspaper' : {},
u'newyork' : {},
u'niepce' : {},
u'norfolk' : {},
u'north' : {},
u'nrw' : {},
u'nuernberg' : {},
u'nuremberg' : {},
u'nyc' : {},
u'nyny' : {},
u'oceanographic' : {},
u'oceanographique' : {},
u'omaha' : {},
u'online' : {},
u'ontario' : {},
u'openair' : {},
u'oregon' : {},
u'oregontrail' : {},
u'otago' : {},
u'oxford' : {},
u'pacific' : {},
u'paderborn' : {},
u'palace' : {},
u'paleo' : {},
u'palmsprings' : {},
u'panama' : {},
u'paris' : {},
u'pasadena' : {},
u'pharmacy' : {},
u'philadelphia' : {},
u'philadelphiaarea' : {},
u'philately' : {},
u'phoenix' : {},
u'photography' : {},
u'pilots' : {},
u'pittsburgh' : {},
u'planetarium' : {},
u'plantation' : {},
u'plants' : {},
u'plaza' : {},
u'portal' : {},
u'portland' : {},
u'portlligat' : {},
u'posts-and-telecommunications' : {},
u'preservation' : {},
u'presidio' : {},
u'press' : {},
u'project' : {},
u'public' : {},
u'pubol' : {},
u'quebec' : {},
u'railroad' : {},
u'railway' : {},
u'research' : {},
u'resistance' : {},
u'riodejaneiro' : {},
u'rochester' : {},
u'rockart' : {},
u'roma' : {},
u'russia' : {},
u'saintlouis' : {},
u'salem' : {},
u'salvadordali' : {},
u'salzburg' : {},
u'sandiego' : {},
u'sanfrancisco' : {},
u'santabarbara' : {},
u'santacruz' : {},
u'santafe' : {},
u'saskatchewan' : {},
u'satx' : {},
u'savannahga' : {},
u'schlesisches' : {},
u'schoenbrunn' : {},
u'schokoladen' : {},
u'school' : {},
u'schweiz' : {},
u'science' : {},
u'science-fiction' : {},
u'scienceandhistory' : {},
u'scienceandindustry' : {},
u'sciencecenter' : {},
u'sciencecenters' : {},
u'sciencehistory' : {},
u'sciences' : {},
u'sciencesnaturelles' : {},
u'scotland' : {},
u'seaport' : {},
u'settlement' : {},
u'settlers' : {},
u'shell' : {},
u'sherbrooke' : {},
u'sibenik' : {},
u'silk' : {},
u'ski' : {},
u'skole' : {},
u'society' : {},
u'sologne' : {},
u'soundandvision' : {},
u'southcarolina' : {},
u'southwest' : {},
u'space' : {},
u'spy' : {},
u'square' : {},
u'stadt' : {},
u'stalbans' : {},
u'starnberg' : {},
u'state' : {},
u'stateofdelaware' : {},
u'station' : {},
u'steam' : {},
u'steiermark' : {},
u'stjohn' : {},
u'stockholm' : {},
u'stpetersburg' : {},
u'stuttgart' : {},
u'suisse' : {},
u'surgeonshall' : {},
u'surrey' : {},
u'svizzera' : {},
u'sweden' : {},
u'sydney' : {},
u'tank' : {},
u'tcm' : {},
u'technology' : {},
u'telekommunikation' : {},
u'television' : {},
u'texas' : {},
u'textile' : {},
u'theater' : {},
u'time' : {},
u'timekeeping' : {},
u'topology' : {},
u'torino' : {},
u'touch' : {},
u'town' : {},
u'transport' : {},
u'tree' : {},
u'trolley' : {},
u'trust' : {},
u'trustee' : {},
u'uhren' : {},
u'ulm' : {},
u'undersea' : {},
u'university' : {},
u'usa' : {},
u'usantiques' : {},
u'usarts' : {},
u'uscountryestate' : {},
u'usculture' : {},
u'usdecorativearts' : {},
u'usgarden' : {},
u'ushistory' : {},
u'ushuaia' : {},
u'uslivinghistory' : {},
u'utah' : {},
u'uvic' : {},
u'valley' : {},
u'vantaa' : {},
u'versailles' : {},
u'viking' : {},
u'village' : {},
u'virginia' : {},
u'virtual' : {},
u'virtuel' : {},
u'vlaanderen' : {},
u'volkenkunde' : {},
u'wales' : {},
u'wallonie' : {},
u'war' : {},
u'washingtondc' : {},
u'watch-and-clock' : {},
u'watchandclock' : {},
u'western' : {},
u'westfalen' : {},
u'whaling' : {},
u'wildlife' : {},
u'williamsburg' : {},
u'windmill' : {},
u'workshop' : {},
u'york' : {},
u'yorkshire' : {},
u'yosemite' : {},
u'youth' : {},
u'zoological' : {},
u'zoology' : {},
u'иком' : {},
u'ירושלים' : {}},
u'mv' : {u'aero' : {},
u'biz' : {},
u'com' : {},
u'coop' : {},
u'edu' : {},
u'gov' : {},
u'info' : {},
u'int' : {},
u'mil' : {},
u'museum' : {},
u'name' : {},
u'net' : {},
u'org' : {},
u'pro' : {}},
u'mw' : {u'ac' : {},
u'biz' : {},
u'co' : {},
u'com' : {},
u'coop' : {},
u'edu' : {},
u'gov' : {},
u'int' : {},
u'museum' : {},
u'net' : {},
u'org' : {}},
u'mx' : {u'com' : {},
u'edu' : {},
u'gob' : {},
u'net' : {},
u'org' : {}},
u'my' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'name' : {},
u'net' : {},
u'org' : {}},
u'mz' : {u'*' : {}},
u'na' : {u'ca' : {},
u'cc' : {},
u'co' : {},
u'com' : {},
u'dr' : {},
u'in' : {},
u'info' : {},
u'mobi' : {},
u'mx' : {},
u'name' : {},
u'or' : {},
u'org' : {},
u'pro' : {},
u'school' : {},
u'tv' : {},
u'us' : {},
u'ws' : {}},
u'name' : {},
u'nc' : {u'asso' : {}},
u'ne' : {},
u'net' : {u'gb' : {},
u'se' : {},
u'uk' : {},
u'za' : {}},
u'nf' : {u'arts' : {},
u'com' : {},
u'firm' : {},
u'info' : {},
u'net' : {},
u'other' : {},
u'per' : {},
u'rec' : {},
u'store' : {},
u'web' : {}},
u'ng' : {u'ac' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'ni' : {u'*' : {}},
u'nl' : {},
u'no' : {u'aa' : {u'gs' : {}},
u'aarborte' : {},
u'aejrie' : {},
u'afjord' : {},
u'agdenes' : {},
u'ah' : {u'gs' : {}},
u'akershus' : {u'nes' : {}},
u'aknoluokta' : {},
u'akrehamn' : {},
u'al' : {},
u'alaheadju' : {},
u'alesund' : {},
u'algard' : {},
u'alstahaug' : {},
u'alta' : {},
u'alvdal' : {},
u'amli' : {},
u'amot' : {},
u'andasuolo' : {},
u'andebu' : {},
u'andoy' : {},
u'andøy' : {},
u'ardal' : {},
u'aremark' : {},
u'arendal' : {},
u'arna' : {},
u'aseral' : {},
u'asker' : {},
u'askim' : {},
u'askoy' : {},
u'askvoll' : {},
u'askøy' : {},
u'asnes' : {},
u'audnedaln' : {},
u'aukra' : {},
u'aure' : {},
u'aurland' : {},
u'aurskog-holand' : {},
u'aurskog-høland' : {},
u'austevoll' : {},
u'austrheim' : {},
u'averoy' : {},
u'averøy' : {},
u'badaddja' : {},
u'bahcavuotna' : {},
u'bahccavuotna' : {},
u'baidar' : {},
u'bajddar' : {},
u'balat' : {},
u'balestrand' : {},
u'ballangen' : {},
u'balsfjord' : {},
u'bamble' : {},
u'bardu' : {},
u'barum' : {},
u'batsfjord' : {},
u'bearalvahki' : {},
u'bearalváhki' : {},
u'beardu' : {},
u'beiarn' : {},
u'berg' : {},
u'bergen' : {},
u'berlevag' : {},
u'berlevåg' : {},
u'bievat' : {},
u'bievát' : {},
u'bindal' : {},
u'birkenes' : {},
u'bjarkoy' : {},
u'bjarkøy' : {},
u'bjerkreim' : {},
u'bjugn' : {},
u'bodo' : {},
u'bodø' : {},
u'bokn' : {},
u'bomlo' : {},
u'bremanger' : {},
u'bronnoy' : {},
u'bronnoysund' : {},
u'brumunddal' : {},
u'bryne' : {},
u'brønnøy' : {},
u'brønnøysund' : {},
u'bu' : {u'gs' : {}},
u'budejju' : {},
u'buskerud' : {u'nes' : {}},
u'bygland' : {},
u'bykle' : {},
u'báhcavuotna' : {},
u'báhccavuotna' : {},
u'báidár' : {},
u'bájddar' : {},
u'bálát' : {},
u'bådåddjå' : {},
u'båtsfjord' : {},
u'bærum' : {},
u'bømlo' : {},
u'cahcesuolo' : {},
u'davvenjarga' : {},
u'davvenjárga' : {},
u'davvesiida' : {},
u'deatnu' : {},
u'dep' : {},
u'dielddanuorri' : {},
u'divtasvuodna' : {},
u'divttasvuotna' : {},
u'donna' : {},
u'dovre' : {},
u'drammen' : {},
u'drangedal' : {},
u'drobak' : {},
u'drøbak' : {},
u'dyroy' : {},
u'dyrøy' : {},
u'dønna' : {},
u'egersund' : {},
u'eid' : {},
u'eidfjord' : {},
u'eidsberg' : {},
u'eidskog' : {},
u'eidsvoll' : {},
u'eigersund' : {},
u'elverum' : {},
u'enebakk' : {},
u'engerdal' : {},
u'etne' : {},
u'etnedal' : {},
u'evenassi' : {},
u'evenes' : {},
u'evenášši' : {},
u'evje-og-hornnes' : {},
u'farsund' : {},
u'fauske' : {},
u'fedje' : {},
u'fet' : {},
u'fetsund' : {},
u'fhs' : {},
u'finnoy' : {},
u'finnøy' : {},
u'fitjar' : {},
u'fjaler' : {},
u'fjell' : {},
u'fla' : {},
u'flakstad' : {},
u'flatanger' : {},
u'flekkefjord' : {},
u'flesberg' : {},
u'flora' : {},
u'floro' : {},
u'florø' : {},
u'flå' : {},
u'fm' : {u'gs' : {}},
u'folkebibl' : {},
u'folldal' : {},
u'forde' : {},
u'forsand' : {},
u'fosnes' : {},
u'frana' : {},
u'fredrikstad' : {},
u'frei' : {},
u'frogn' : {},
u'froland' : {},
u'frosta' : {},
u'froya' : {},
u'fræna' : {},
u'frøya' : {},
u'fuoisku' : {},
u'fuossko' : {},
u'fusa' : {},
u'fylkesbibl' : {},
u'fyresdal' : {},
u'førde' : {},
u'gaivuotna' : {},
u'galsa' : {},
u'gamvik' : {},
u'gangaviika' : {},
u'gaular' : {},
u'gausdal' : {},
u'giehtavuoatna' : {},
u'gildeskal' : {},
u'gildeskål' : {},
u'giske' : {},
u'gjemnes' : {},
u'gjerdrum' : {},
u'gjerstad' : {},
u'gjesdal' : {},
u'gjovik' : {},
u'gjøvik' : {},
u'gloppen' : {},
u'gol' : {},
u'gran' : {},
u'grane' : {},
u'granvin' : {},
u'gratangen' : {},
u'grimstad' : {},
u'grong' : {},
u'grue' : {},
u'gulen' : {},
u'guovdageaidnu' : {},
u'gáivuotna' : {},
u'gálsá' : {},
u'gáŋgaviika' : {},
u'ha' : {},
u'habmer' : {},
u'hadsel' : {},
u'hagebostad' : {},
u'halden' : {},
u'halsa' : {},
u'hamar' : {},
u'hamaroy' : {},
u'hammarfeasta' : {},
u'hammerfest' : {},
u'hapmir' : {},
u'haram' : {},
u'hareid' : {},
u'harstad' : {},
u'hasvik' : {},
u'hattfjelldal' : {},
u'haugesund' : {},
u'hedmark' : {u'os' : {},
u'valer' : {},
u'våler' : {}},
u'hemne' : {},
u'hemnes' : {},
u'hemsedal' : {},
u'herad' : {},
u'hitra' : {},
u'hjartdal' : {},
u'hjelmeland' : {},
u'hl' : {u'gs' : {}},
u'hm' : {u'gs' : {}},
u'hobol' : {},
u'hobøl' : {},
u'hof' : {},
u'hokksund' : {},
u'hol' : {},
u'hole' : {},
u'holmestrand' : {},
u'holtalen' : {},
u'holtålen' : {},
u'honefoss' : {},
u'hordaland' : {u'os' : {}},
u'hornindal' : {},
u'horten' : {},
u'hoyanger' : {},
u'hoylandet' : {},
u'hurdal' : {},
u'hurum' : {},
u'hvaler' : {},
u'hyllestad' : {},
u'hábmer' : {},
u'hámmárfeasta' : {},
u'hápmir' : {},
u'hå' : {},
u'hægebostad' : {},
u'hønefoss' : {},
u'høyanger' : {},
u'høylandet' : {},
u'ibestad' : {},
u'idrett' : {},
u'inderoy' : {},
u'inderøy' : {},
u'iveland' : {},
u'ivgu' : {},
u'jan-mayen' : {u'gs' : {}},
u'jessheim' : {},
u'jevnaker' : {},
u'jolster' : {},
u'jondal' : {},
u'jorpeland' : {},
u'jølster' : {},
u'jørpeland' : {},
u'kafjord' : {},
u'karasjohka' : {},
u'karasjok' : {},
u'karlsoy' : {},
u'karmoy' : {},
u'karmøy' : {},
u'kautokeino' : {},
u'kirkenes' : {},
u'klabu' : {},
u'klepp' : {},
u'klæbu' : {},
u'kommune' : {},
u'kongsberg' : {},
u'kongsvinger' : {},
u'kopervik' : {},
u'kraanghke' : {},
u'kragero' : {},
u'kragerø' : {},
u'kristiansand' : {},
u'kristiansund' : {},
u'krodsherad' : {},
u'krokstadelva' : {},
u'kråanghke' : {},
u'krødsherad' : {},
u'kvafjord' : {},
u'kvalsund' : {},
u'kvam' : {},
u'kvanangen' : {},
u'kvinesdal' : {},
u'kvinnherad' : {},
u'kviteseid' : {},
u'kvitsoy' : {},
u'kvitsøy' : {},
u'kvæfjord' : {},
u'kvænangen' : {},
u'kárášjohka' : {},
u'kåfjord' : {},
u'laakesvuemie' : {},
u'lahppi' : {},
u'langevag' : {},
u'langevåg' : {},
u'lardal' : {},
u'larvik' : {},
u'lavagis' : {},
u'lavangen' : {},
u'leangaviika' : {},
u'leaŋgaviika' : {},
u'lebesby' : {},
u'leikanger' : {},
u'leirfjord' : {},
u'leirvik' : {},
u'leka' : {},
u'leksvik' : {},
u'lenvik' : {},
u'lerdal' : {},
u'lesja' : {},
u'levanger' : {},
u'lier' : {},
u'lierne' : {},
u'lillehammer' : {},
u'lillesand' : {},
u'lindas' : {},
u'lindesnes' : {},
u'lindås' : {},
u'loabat' : {},
u'loabát' : {},
u'lodingen' : {},
u'lom' : {},
u'loppa' : {},
u'lorenskog' : {},
u'loten' : {},
u'lund' : {},
u'lunner' : {},
u'luroy' : {},
u'lurøy' : {},
u'luster' : {},
u'lyngdal' : {},
u'lyngen' : {},
u'láhppi' : {},
u'lærdal' : {},
u'lødingen' : {},
u'lørenskog' : {},
u'løten' : {},
u'malatvuopmi' : {},
u'malselv' : {},
u'malvik' : {},
u'mandal' : {},
u'marker' : {},
u'marnardal' : {},
u'masfjorden' : {},
u'masoy' : {},
u'matta-varjjat' : {},
u'meland' : {},
u'meldal' : {},
u'melhus' : {},
u'meloy' : {},
u'meløy' : {},
u'meraker' : {},
u'meråker' : {},
u'midsund' : {},
u'midtre-gauldal' : {},
u'mil' : {},
u'mjondalen' : {},
u'mjøndalen' : {},
u'mo-i-rana' : {},
u'moareke' : {},
u'modalen' : {},
u'modum' : {},
u'molde' : {},
u'more-og-romsdal' : {u'heroy' : {},
u'sande' : {}},
u'mosjoen' : {},
u'mosjøen' : {},
u'moskenes' : {},
u'moss' : {},
u'mosvik' : {},
u'moåreke' : {},
u'mr' : {u'gs' : {}},
u'muosat' : {},
u'muosát' : {},
u'museum' : {},
u'málatvuopmi' : {},
u'mátta-várjjat' : {},
u'målselv' : {},
u'måsøy' : {},
u'møre-og-romsdal' : {u'herøy' : {},
u'sande' : {}},
u'naamesjevuemie' : {},
u'namdalseid' : {},
u'namsos' : {},
u'namsskogan' : {},
u'nannestad' : {},
u'naroy' : {},
u'narviika' : {},
u'narvik' : {},
u'naustdal' : {},
u'navuotna' : {},
u'nedre-eiker' : {},
u'nesna' : {},
u'nesodden' : {},
u'nesoddtangen' : {},
u'nesseby' : {},
u'nesset' : {},
u'nissedal' : {},
u'nittedal' : {},
u'nl' : {u'gs' : {}},
u'nord-aurdal' : {},
u'nord-fron' : {},
u'nord-odal' : {},
u'norddal' : {},
u'nordkapp' : {},
u'nordland' : {u'bo' : {},
u'bø' : {},
u'heroy' : {},
u'herøy' : {}},
u'nordre-land' : {},
u'nordreisa' : {},
u'nore-og-uvdal' : {},
u'notodden' : {},
u'notteroy' : {},
u'nt' : {u'gs' : {}},
u'návuotna' : {},
u'nååmesjevuemie' : {},
u'nærøy' : {},
u'nøtterøy' : {},
u'odda' : {},
u'of' : {u'gs' : {}},
u'oksnes' : {},
u'ol' : {u'gs' : {}},
u'omasvuotna' : {},
u'oppdal' : {},
u'oppegard' : {},
u'oppegård' : {},
u'orkanger' : {},
u'orkdal' : {},
u'orland' : {},
u'orskog' : {},
u'orsta' : {},
u'osen' : {},
u'oslo' : {u'gs' : {}},
u'osoyro' : {},
u'osteroy' : {},
u'osterøy' : {},
u'ostfold' : {u'valer' : {}},
u'ostre-toten' : {},
u'osøyro' : {},
u'overhalla' : {},
u'ovre-eiker' : {},
u'oyer' : {},
u'oygarden' : {},
u'oystre-slidre' : {},
u'porsanger' : {},
u'porsangu' : {},
u'porsgrunn' : {},
u'porsáŋgu' : {},
u'priv' : {},
u'rade' : {},
u'radoy' : {},
u'radøy' : {},
u'rahkkeravju' : {},
u'raholt' : {},
u'raisa' : {},
u'rakkestad' : {},
u'ralingen' : {},
u'rana' : {},
u'randaberg' : {},
u'rauma' : {},
u'rendalen' : {},
u'rennebu' : {},
u'rennesoy' : {},
u'rennesøy' : {},
u'rindal' : {},
u'ringebu' : {},
u'ringerike' : {},
u'ringsaker' : {},
u'risor' : {},
u'rissa' : {},
u'risør' : {},
u'rl' : {u'gs' : {}},
u'roan' : {},
u'rodoy' : {},
u'rollag' : {},
u'romsa' : {},
u'romskog' : {},
u'roros' : {},
u'rost' : {},
u'royken' : {},
u'royrvik' : {},
u'ruovat' : {},
u'rygge' : {},
u'ráhkkerávju' : {},
u'ráisa' : {},
u'råde' : {},
u'råholt' : {},
u'rælingen' : {},
u'rødøy' : {},
u'rømskog' : {},
u'røros' : {},
u'røst' : {},
u'røyken' : {},
u'røyrvik' : {},
u'salangen' : {},
u'salat' : {},
u'saltdal' : {},
u'samnanger' : {},
u'sandefjord' : {},
u'sandnes' : {},
u'sandnessjoen' : {},
u'sandnessjøen' : {},
u'sandoy' : {},
u'sandøy' : {},
u'sarpsborg' : {},
u'sauda' : {},
u'sauherad' : {},
u'sel' : {},
u'selbu' : {},
u'selje' : {},
u'seljord' : {},
u'sf' : {u'gs' : {}},
u'siellak' : {},
u'sigdal' : {},
u'siljan' : {},
u'sirdal' : {},
u'skanit' : {},
u'skanland' : {},
u'skaun' : {},
u'skedsmo' : {},
u'skedsmokorset' : {},
u'ski' : {},
u'skien' : {},
u'skierva' : {},
u'skiervá' : {},
u'skiptvet' : {},
u'skjak' : {},
u'skjervoy' : {},
u'skjervøy' : {},
u'skjåk' : {},
u'skodje' : {},
u'skánit' : {},
u'skånland' : {},
u'slattum' : {},
u'smola' : {},
u'smøla' : {},
u'snaase' : {},
u'snasa' : {},
u'snillfjord' : {},
u'snoasa' : {},
u'snåase' : {},
u'snåsa' : {},
u'sogndal' : {},
u'sogne' : {},
u'sokndal' : {},
u'sola' : {},
u'solund' : {},
u'somna' : {},
u'sondre-land' : {},
u'songdalen' : {},
u'sor-aurdal' : {},
u'sor-fron' : {},
u'sor-odal' : {},
u'sor-varanger' : {},
u'sorfold' : {},
u'sorreisa' : {},
u'sortland' : {},
u'sorum' : {},
u'spjelkavik' : {},
u'spydeberg' : {},
u'st' : {u'gs' : {}},
u'stange' : {},
u'stat' : {},
u'stathelle' : {},
u'stavanger' : {},
u'stavern' : {},
u'steigen' : {},
u'steinkjer' : {},
u'stjordal' : {},
u'stjordalshalsen' : {},
u'stjørdal' : {},
u'stjørdalshalsen' : {},
u'stokke' : {},
u'stor-elvdal' : {},
u'stord' : {},
u'stordal' : {},
u'storfjord' : {},
u'strand' : {},
u'stranda' : {},
u'stryn' : {},
u'sula' : {},
u'suldal' : {},
u'sund' : {},
u'sunndal' : {},
u'surnadal' : {},
u'svalbard' : {u'gs' : {}},
u'sveio' : {},
u'svelvik' : {},
u'sykkylven' : {},
u'sálat' : {},
u'sálát' : {},
u'søgne' : {},
u'sømna' : {},
u'søndre-land' : {},
u'sør-aurdal' : {},
u'sør-fron' : {},
u'sør-odal' : {},
u'sør-varanger' : {},
u'sørfold' : {},
u'sørreisa' : {},
u'sørum' : {},
u'tana' : {},
u'tananger' : {},
u'telemark' : {u'bo' : {},
u'bø' : {}},
u'time' : {},
u'tingvoll' : {},
u'tinn' : {},
u'tjeldsund' : {},
u'tjome' : {},
u'tjøme' : {},
u'tm' : {u'gs' : {}},
u'tokke' : {},
u'tolga' : {},
u'tonsberg' : {},
u'torsken' : {},
u'tr' : {u'gs' : {}},
u'trana' : {},
u'tranby' : {},
u'tranoy' : {},
u'tranøy' : {},
u'troandin' : {},
u'trogstad' : {},
u'tromsa' : {},
u'tromso' : {},
u'tromsø' : {},
u'trondheim' : {},
u'trysil' : {},
u'træna' : {},
u'trøgstad' : {},
u'tvedestrand' : {},
u'tydal' : {},
u'tynset' : {},
u'tysfjord' : {},
u'tysnes' : {},
u'tysvar' : {},
u'tysvær' : {},
u'tønsberg' : {},
u'ullensaker' : {},
u'ullensvang' : {},
u'ulvik' : {},
u'unjarga' : {},
u'unjárga' : {},
u'utsira' : {},
u'va' : {u'gs' : {}},
u'vaapste' : {},
u'vadso' : {},
u'vadsø' : {},
u'vaga' : {},
u'vagan' : {},
u'vagsoy' : {},
u'vaksdal' : {},
u'valle' : {},
u'vang' : {},
u'vanylven' : {},
u'vardo' : {},
u'vardø' : {},
u'varggat' : {},
u'varoy' : {},
u'vefsn' : {},
u'vega' : {},
u'vegarshei' : {},
u'vegårshei' : {},
u'vennesla' : {},
u'verdal' : {},
u'verran' : {},
u'vestby' : {},
u'vestfold' : {u'sande' : {}},
u'vestnes' : {},
u'vestre-slidre' : {},
u'vestre-toten' : {},
u'vestvagoy' : {},
u'vestvågøy' : {},
u'vevelstad' : {},
u'vf' : {u'gs' : {}},
u'vgs' : {},
u'vik' : {},
u'vikna' : {},
u'vindafjord' : {},
u'voagat' : {},
u'volda' : {},
u'voss' : {},
u'vossevangen' : {},
u'várggát' : {},
u'vågan' : {},
u'vågsøy' : {},
u'vågå' : {},
u'værøy' : {},
u'ákŋoluokta' : {},
u'álaheadju' : {},
u'áltá' : {},
u'åfjord' : {},
u'åkrehamn' : {},
u'ål' : {},
u'ålesund' : {},
u'ålgård' : {},
u'åmli' : {},
u'åmot' : {},
u'årdal' : {},
u'ås' : {},
u'åseral' : {},
u'åsnes' : {},
u'øksnes' : {},
u'ørland' : {},
u'ørskog' : {},
u'ørsta' : {},
u'østfold' : {u'våler' : {}},
u'østre-toten' : {},
u'øvre-eiker' : {},
u'øyer' : {},
u'øygarden' : {},
u'øystre-slidre' : {},
u'čáhcesuolo' : {}},
u'np' : {u'*' : {}},
u'nr' : {u'biz' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'info' : {},
u'net' : {},
u'org' : {}},
u'nu' : {},
u'nz' : {u'*' : {}},
u'om' : {u'*' : {},
u'mediaphone' : {u'!' : {}},
u'nawras' : {u'!' : {}},
u'nawrastelecom' : {u'!' : {}},
u'omanmobile' : {u'!' : {}},
u'omanpost' : {u'!' : {}},
u'omantel' : {u'!' : {}},
u'rakpetroleum' : {u'!' : {}},
u'siemens' : {u'!' : {}},
u'songfest' : {u'!' : {}},
u'statecouncil' : {u'!' : {}}},
u'org' : {u'ae' : {},
u'za' : {}},
u'pa' : {u'abo' : {},
u'ac' : {},
u'com' : {},
u'edu' : {},
u'gob' : {},
u'ing' : {},
u'med' : {},
u'net' : {},
u'nom' : {},
u'org' : {},
u'sld' : {}},
u'pe' : {u'com' : {},
u'edu' : {},
u'gob' : {},
u'mil' : {},
u'net' : {},
u'nom' : {},
u'org' : {}},
u'pf' : {u'com' : {},
u'edu' : {},
u'org' : {}},
u'pg' : {u'*' : {}},
u'ph' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'i' : {},
u'mil' : {},
u'net' : {},
u'ngo' : {},
u'org' : {}},
u'pk' : {u'biz' : {},
u'com' : {},
u'edu' : {},
u'fam' : {},
u'gob' : {},
u'gok' : {},
u'gon' : {},
u'gop' : {},
u'gos' : {},
u'gov' : {},
u'info' : {},
u'net' : {},
u'org' : {},
u'web' : {}},
u'pl' : {u'6bone' : {},
u'agro' : {},
u'aid' : {},
u'art' : {},
u'atm' : {},
u'augustow' : {},
u'auto' : {},
u'babia-gora' : {},
u'bedzin' : {},
u'beskidy' : {},
u'bialowieza' : {},
u'bialystok' : {},
u'bielawa' : {},
u'bieszczady' : {},
u'biz' : {},
u'boleslawiec' : {},
u'bydgoszcz' : {},
u'bytom' : {},
u'cieszyn' : {},
u'co' : {},
u'com' : {},
u'czeladz' : {},
u'czest' : {},
u'dlugoleka' : {},
u'edu' : {},
u'elblag' : {},
u'elk' : {},
u'gda' : {},
u'gdansk' : {},
u'gdynia' : {},
u'gliwice' : {},
u'glogow' : {},
u'gmina' : {},
u'gniezno' : {},
u'gorlice' : {},
u'gov' : {u'pa' : {},
u'po' : {},
u'so' : {},
u'sr' : {},
u'starostwo' : {},
u'ug' : {},
u'um' : {},
u'upow' : {},
u'uw' : {}},
u'grajewo' : {},
u'gsm' : {},
u'ilawa' : {},
u'info' : {},
u'irc' : {},
u'jaworzno' : {},
u'jelenia-gora' : {},
u'jgora' : {},
u'kalisz' : {},
u'karpacz' : {},
u'kartuzy' : {},
u'kaszuby' : {},
u'katowice' : {},
u'kazimierz-dolny' : {},
u'kepno' : {},
u'ketrzyn' : {},
u'klodzko' : {},
u'kobierzyce' : {},
u'kolobrzeg' : {},
u'konin' : {},
u'konskowola' : {},
u'krakow' : {},
u'kutno' : {},
u'lapy' : {},
u'lebork' : {},
u'legnica' : {},
u'lezajsk' : {},
u'limanowa' : {},
u'lomza' : {},
u'lowicz' : {},
u'lubin' : {},
u'lukow' : {},
u'mail' : {},
u'malbork' : {},
u'malopolska' : {},
u'mazowsze' : {},
u'mazury' : {},
u'mbone' : {},
u'med' : {},
u'media' : {},
u'miasta' : {},
u'mielec' : {},
u'mielno' : {},
u'mil' : {},
u'mragowo' : {},
u'naklo' : {},
u'net' : {},
u'ngo' : {},
u'nieruchomosci' : {},
u'nom' : {},
u'nowaruda' : {},
u'nysa' : {},
u'olawa' : {},
u'olecko' : {},
u'olkusz' : {},
u'olsztyn' : {},
u'opoczno' : {},
u'opole' : {},
u'org' : {},
u'ostroda' : {},
u'ostroleka' : {},
u'ostrowiec' : {},
u'ostrowwlkp' : {},
u'pc' : {},
u'pila' : {},
u'pisz' : {},
u'podhale' : {},
u'podlasie' : {},
u'polkowice' : {},
u'pomorskie' : {},
u'pomorze' : {},
u'powiat' : {},
u'poznan' : {},
u'priv' : {},
u'prochowice' : {},
u'pruszkow' : {},
u'przeworsk' : {},
u'pulawy' : {},
u'radom' : {},
u'rawa-maz' : {},
u'realestate' : {},
u'rel' : {},
u'rybnik' : {},
u'rzeszow' : {},
u'sanok' : {},
u'sejny' : {},
u'sex' : {},
u'shop' : {},
u'siedlce' : {},
u'sklep' : {},
u'skoczow' : {},
u'slask' : {},
u'slupsk' : {},
u'sopot' : {},
u'sos' : {},
u'sosnowiec' : {},
u'stalowa-wola' : {},
u'starachowice' : {},
u'stargard' : {},
u'suwalki' : {},
u'swidnica' : {},
u'swiebodzin' : {},
u'swinoujscie' : {},
u'szczecin' : {},
u'szczytno' : {},
u'szkola' : {},
u'targi' : {},
u'tarnobrzeg' : {},
u'tgory' : {},
u'tm' : {},
u'tourism' : {},
u'travel' : {},
u'turek' : {},
u'turystyka' : {},
u'tychy' : {},
u'usenet' : {},
u'ustka' : {},
u'walbrzych' : {},
u'warmia' : {},
u'warszawa' : {},
u'waw' : {},
u'wegrow' : {},
u'wielun' : {},
u'wlocl' : {},
u'wloclawek' : {},
u'wodzislaw' : {},
u'wolomin' : {},
u'wroc' : {},
u'wroclaw' : {},
u'zachpomor' : {},
u'zagan' : {},
u'zakopane' : {},
u'zarow' : {},
u'zgora' : {},
u'zgorzelec' : {}},
u'pn' : {u'co' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'pr' : {u'ac' : {},
u'biz' : {},
u'com' : {},
u'edu' : {},
u'est' : {},
u'gov' : {},
u'info' : {},
u'isla' : {},
u'name' : {},
u'net' : {},
u'org' : {},
u'pro' : {},
u'prof' : {}},
u'pro' : {u'aca' : {},
u'bar' : {},
u'cpa' : {},
u'eng' : {},
u'jur' : {},
u'law' : {},
u'med' : {}},
u'ps' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {},
u'plo' : {},
u'sec' : {}},
u'pt' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'int' : {},
u'net' : {},
u'nome' : {},
u'org' : {},
u'publ' : {}},
u'pw' : {u'belau' : {},
u'co' : {},
u'ed' : {},
u'go' : {},
u'ne' : {},
u'or' : {}},
u'py' : {u'*' : {}},
u'qa' : {u'*' : {}},
u're' : {u'asso' : {},
u'com' : {},
u'nom' : {}},
u'ro' : {u'arts' : {},
u'com' : {},
u'firm' : {},
u'info' : {},
u'nom' : {},
u'nt' : {},
u'org' : {},
u'rec' : {},
u'store' : {},
u'tm' : {},
u'www' : {}},
u'rs' : {u'ac' : {},
u'co' : {},
u'edu' : {},
u'gov' : {},
u'in' : {},
u'org' : {}},
u'ru' : {u'ac' : {},
u'adygeya' : {},
u'altai' : {},
u'amur' : {},
u'amursk' : {},
u'arkhangelsk' : {},
u'astrakhan' : {},
u'baikal' : {},
u'bashkiria' : {},
u'belgorod' : {},
u'bir' : {},
u'bryansk' : {},
u'buryatia' : {},
u'cbg' : {},
u'chel' : {},
u'chelyabinsk' : {},
u'chita' : {},
u'chukotka' : {},
u'chuvashia' : {},
u'cmw' : {},
u'com' : {},
u'dagestan' : {},
u'dudinka' : {},
u'e-burg' : {},
u'edu' : {},
u'fareast' : {},
u'gov' : {},
u'grozny' : {},
u'int' : {},
u'irkutsk' : {},
u'ivanovo' : {},
u'izhevsk' : {},
u'jamal' : {},
u'jar' : {},
u'joshkar-ola' : {},
u'k-uralsk' : {},
u'kalmykia' : {},
u'kaluga' : {},
u'kamchatka' : {},
u'karelia' : {},
u'kazan' : {},
u'kchr' : {},
u'kemerovo' : {},
u'khabarovsk' : {},
u'khakassia' : {},
u'khv' : {},
u'kirov' : {},
u'kms' : {},
u'koenig' : {},
u'komi' : {},
u'kostroma' : {},
u'krasnoyarsk' : {},
u'kuban' : {},
u'kurgan' : {},
u'kursk' : {},
u'kustanai' : {},
u'kuzbass' : {},
u'lipetsk' : {},
u'magadan' : {},
u'magnitka' : {},
u'mari' : {},
u'mari-el' : {},
u'marine' : {},
u'mil' : {},
u'mordovia' : {},
u'mosreg' : {},
u'msk' : {},
u'murmansk' : {},
u'mytis' : {},
u'nakhodka' : {},
u'nalchik' : {},
u'net' : {},
u'nkz' : {},
u'nnov' : {},
u'norilsk' : {},
u'nov' : {},
u'novosibirsk' : {},
u'nsk' : {},
u'omsk' : {},
u'orenburg' : {},
u'org' : {},
u'oryol' : {},
u'oskol' : {},
u'palana' : {},
u'penza' : {},
u'perm' : {},
u'pp' : {},
u'pskov' : {},
u'ptz' : {},
u'pyatigorsk' : {},
u'rnd' : {},
u'rubtsovsk' : {},
u'ryazan' : {},
u'sakhalin' : {},
u'samara' : {},
u'saratov' : {},
u'simbirsk' : {},
u'smolensk' : {},
u'snz' : {},
u'spb' : {},
u'stavropol' : {},
u'stv' : {},
u'surgut' : {},
u'syzran' : {},
u'tambov' : {},
u'tatarstan' : {},
u'test' : {},
u'tom' : {},
u'tomsk' : {},
u'tsaritsyn' : {},
u'tsk' : {},
u'tula' : {},
u'tuva' : {},
u'tver' : {},
u'tyumen' : {},
u'udm' : {},
u'udmurtia' : {},
u'ulan-ude' : {},
u'vdonsk' : {},
u'vladikavkaz' : {},
u'vladimir' : {},
u'vladivostok' : {},
u'volgograd' : {},
u'vologda' : {},
u'voronezh' : {},
u'vrn' : {},
u'vyatka' : {},
u'yakutia' : {},
u'yamal' : {},
u'yaroslavl' : {},
u'yekaterinburg' : {},
u'yuzhno-sakhalinsk' : {},
u'zgrad' : {}},
u'rw' : {u'ac' : {},
u'co' : {},
u'com' : {},
u'edu' : {},
u'gouv' : {},
u'gov' : {},
u'int' : {},
u'mil' : {},
u'net' : {}},
u'sa' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'med' : {},
u'net' : {},
u'org' : {},
u'pub' : {},
u'sch' : {}},
u'sb' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'sc' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'sd' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'info' : {},
u'med' : {},
u'net' : {},
u'org' : {}},
u'se' : {u'a' : {},
u'ac' : {},
u'b' : {},
u'bd' : {},
u'brand' : {},
u'c' : {},
u'd' : {},
u'e' : {},
u'f' : {},
u'fh' : {},
u'fhsk' : {},
u'fhv' : {},
u'g' : {},
u'h' : {},
u'i' : {},
u'k' : {},
u'komforb' : {},
u'kommunalforbund' : {},
u'komvux' : {},
u'l' : {},
u'lanbib' : {},
u'm' : {},
u'n' : {},
u'naturbruksgymn' : {},
u'o' : {},
u'org' : {},
u'p' : {},
u'parti' : {},
u'pp' : {},
u'press' : {},
u'r' : {},
u's' : {},
u'sshn' : {},
u't' : {},
u'tm' : {},
u'u' : {},
u'w' : {},
u'x' : {},
u'y' : {},
u'z' : {}},
u'sg' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {},
u'per' : {}},
u'sh' : {},
u'si' : {},
u'sk' : {},
u'sl' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'sm' : {},
u'sn' : {u'art' : {},
u'com' : {},
u'edu' : {},
u'gouv' : {},
u'org' : {},
u'perso' : {},
u'univ' : {}},
u'so' : {u'com' : {},
u'net' : {},
u'org' : {}},
u'sr' : {},
u'st' : {u'co' : {},
u'com' : {},
u'consulado' : {},
u'edu' : {},
u'embaixada' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {},
u'principe' : {},
u'saotome' : {},
u'store' : {}},
u'su' : {},
u'sv' : {u'*' : {}},
u'sy' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {}},
u'sz' : {u'ac' : {},
u'co' : {},
u'org' : {}},
u'tc' : {},
u'td' : {},
u'tel' : {},
u'tf' : {},
u'tg' : {},
u'th' : {u'ac' : {},
u'co' : {},
u'go' : {},
u'in' : {},
u'mi' : {},
u'net' : {},
u'or' : {}},
u'tj' : {u'ac' : {},
u'biz' : {},
u'co' : {},
u'com' : {},
u'edu' : {},
u'go' : {},
u'gov' : {},
u'int' : {},
u'mil' : {},
u'name' : {},
u'net' : {},
u'nic' : {},
u'org' : {},
u'test' : {},
u'web' : {}},
u'tk' : {},
u'tl' : {u'gov' : {}},
u'tm' : {},
u'tn' : {u'agrinet' : {},
u'com' : {},
u'defense' : {},
u'edunet' : {},
u'ens' : {},
u'fin' : {},
u'gov' : {},
u'ind' : {},
u'info' : {},
u'intl' : {},
u'mincom' : {},
u'nat' : {},
u'net' : {},
u'org' : {},
u'perso' : {},
u'rnrt' : {},
u'rns' : {},
u'rnu' : {},
u'tourism' : {},
u'turen' : {}},
u'to' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {}},
u'tr' : {u'*' : {},
u'nc' : {u'gov' : {}},
u'nic' : {u'!' : {}},
u'tsk' : {u'!' : {}}},
u'travel' : {},
u'tt' : {u'aero' : {},
u'biz' : {},
u'co' : {},
u'com' : {},
u'coop' : {},
u'edu' : {},
u'gov' : {},
u'info' : {},
u'int' : {},
u'jobs' : {},
u'mobi' : {},
u'museum' : {},
u'name' : {},
u'net' : {},
u'org' : {},
u'pro' : {},
u'travel' : {}},
u'tv' : {},
u'tw' : {u'club' : {},
u'com' : {},
u'ebiz' : {},
u'edu' : {},
u'game' : {},
u'gov' : {},
u'idv' : {},
u'mil' : {},
u'net' : {},
u'org' : {},
u'商業' : {},
u'組織' : {},
u'網路' : {}},
u'tz' : {u'ac' : {},
u'co' : {},
u'go' : {},
u'mil' : {},
u'ne' : {},
u'or' : {},
u'sc' : {}},
u'ua' : {u'cherkassy' : {},
u'chernigov' : {},
u'chernovtsy' : {},
u'ck' : {},
u'cn' : {},
u'com' : {},
u'crimea' : {},
u'cv' : {},
u'dn' : {},
u'dnepropetrovsk' : {},
u'donetsk' : {},
u'dp' : {},
u'edu' : {},
u'gov' : {},
u'if' : {},
u'in' : {},
u'ivano-frankivsk' : {},
u'kh' : {},
u'kharkov' : {},
u'kherson' : {},
u'khmelnitskiy' : {},
u'kiev' : {},
u'kirovograd' : {},
u'km' : {},
u'kr' : {},
u'ks' : {},
u'kv' : {},
u'lg' : {},
u'lugansk' : {},
u'lutsk' : {},
u'lviv' : {},
u'mk' : {},
u'net' : {},
u'nikolaev' : {},
u'od' : {},
u'odessa' : {},
u'org' : {},
u'pl' : {},
u'poltava' : {},
u'rovno' : {},
u'rv' : {},
u'sebastopol' : {},
u'sumy' : {},
u'te' : {},
u'ternopil' : {},
u'uzhgorod' : {},
u'vinnica' : {},
u'vn' : {},
u'zaporizhzhe' : {},
u'zhitomir' : {},
u'zp' : {},
u'zt' : {}},
u'ug' : {u'ac' : {},
u'co' : {},
u'go' : {},
u'ne' : {},
u'or' : {},
u'sc' : {}},
u'uk' : {u'*' : {},
u'bl' : {u'!' : {}},
u'british-library' : {u'!' : {}},
u'icnet' : {u'!' : {}},
u'jet' : {u'!' : {}},
u'national-library-scotland' : {u'!' : {}},
u'nel' : {u'!' : {}},
u'nhs' : {u'!' : {}},
u'nls' : {u'!' : {}},
u'parliament' : {u'!' : {}},
u'sch' : {u'*' : {}}},
u'us' : {u'ak' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'al' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ar' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'as' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'az' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ca' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'co' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ct' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'dc' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'de' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'dni' : {},
u'fed' : {},
u'fl' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ga' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'gu' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'hi' : {u'cc' : {},
u'lib' : {}},
u'ia' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'id' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'il' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'in' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'isa' : {},
u'kids' : {},
u'ks' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ky' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'la' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ma' : {u'cc' : {},
u'k12' : {u'chtr' : {},
u'paroch' : {},
u'pvt' : {}},
u'lib' : {}},
u'md' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'me' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'mi' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'mn' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'mo' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ms' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'mt' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'nc' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'nd' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ne' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'nh' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'nj' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'nm' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'nsn' : {},
u'nv' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ny' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'oh' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ok' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'or' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'pa' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'pr' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ri' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'sc' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'sd' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'tn' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'tx' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'ut' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'va' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'vi' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'vt' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'wa' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'wi' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'wv' : {u'cc' : {},
u'k12' : {},
u'lib' : {}},
u'wy' : {u'cc' : {},
u'k12' : {},
u'lib' : {}}},
u'uy' : {u'*' : {}},
u'uz' : {u'co' : {},
u'com' : {}},
u'va' : {},
u'vc' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'mil' : {},
u'net' : {},
u'org' : {}},
u've' : {u'*' : {}},
u'vg' : {},
u'vi' : {u'co' : {},
u'com' : {},
u'k12' : {},
u'net' : {},
u'org' : {}},
u'vn' : {u'ac' : {},
u'biz' : {},
u'com' : {},
u'edu' : {},
u'gov' : {},
u'health' : {},
u'info' : {},
u'int' : {},
u'name' : {},
u'net' : {},
u'org' : {},
u'pro' : {}},
u'vu' : {},
u'ws' : {u'com' : {},
u'edu' : {},
u'gov' : {},
u'net' : {},
u'org' : {}},
u'ye' : {u'*' : {}},
u'yu' : {u'*' : {}},
u'za' : {u'*' : {}},
u'zm' : {u'*' : {}},
u'zw' : {u'*' : {}},
u'рф' : {},
u'الاردن' : {},
u'السعودية' : {},
u'امارات' : {},
u'تونس' : {},
u'فلسطين' : {},
u'قطر' : {},
u'مصر' : {},
u'இலங்கை' : {},
u'சிங்கப்பூர்' : {},
u'ලංකා' : {},
u'ไทย' : {},
u'中国' : {},
u'中國' : {},
u'台湾' : {},
u'台灣' : {},
u'新加坡' : {},
u'香港' : {}}
