#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class Seed:
  """
  Attributes:
   - url
   - content_group
   - pl_group
   - max_idepth
   - max_xdepth
   - cur_idepth
   - cur_xdepth
   - priority
   - crawl_interval
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'url', None, None, ), # 1
    (2, TType.STRING, 'content_group', None, None, ), # 2
    (3, TType.STRING, 'pl_group', None, None, ), # 3
    (4, TType.I32, 'max_idepth', None, 0, ), # 4
    (5, TType.I32, 'max_xdepth', None, 0, ), # 5
    (6, TType.I32, 'cur_idepth', None, 0, ), # 6
    (7, TType.I32, 'cur_xdepth', None, 0, ), # 7
    (8, TType.I32, 'priority', None, None, ), # 8
    (9, TType.I32, 'crawl_interval', None, 10, ), # 9
  )

  def __init__(self, url=None, content_group=None, pl_group=None, max_idepth=thrift_spec[4][4], max_xdepth=thrift_spec[5][4], cur_idepth=thrift_spec[6][4], cur_xdepth=thrift_spec[7][4], priority=None, crawl_interval=thrift_spec[9][4],):
    self.url = url
    self.content_group = content_group
    self.pl_group = pl_group
    self.max_idepth = max_idepth
    self.max_xdepth = max_xdepth
    self.cur_idepth = cur_idepth
    self.cur_xdepth = cur_xdepth
    self.priority = priority
    self.crawl_interval = crawl_interval

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.url = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.content_group = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.pl_group = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.max_idepth = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.max_xdepth = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.cur_idepth = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.I32:
          self.cur_xdepth = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.I32:
          self.priority = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.I32:
          self.crawl_interval = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Seed')
    if self.url != None:
      oprot.writeFieldBegin('url', TType.STRING, 1)
      oprot.writeString(self.url)
      oprot.writeFieldEnd()
    if self.content_group != None:
      oprot.writeFieldBegin('content_group', TType.STRING, 2)
      oprot.writeString(self.content_group)
      oprot.writeFieldEnd()
    if self.pl_group != None:
      oprot.writeFieldBegin('pl_group', TType.STRING, 3)
      oprot.writeString(self.pl_group)
      oprot.writeFieldEnd()
    if self.max_idepth != None:
      oprot.writeFieldBegin('max_idepth', TType.I32, 4)
      oprot.writeI32(self.max_idepth)
      oprot.writeFieldEnd()
    if self.max_xdepth != None:
      oprot.writeFieldBegin('max_xdepth', TType.I32, 5)
      oprot.writeI32(self.max_xdepth)
      oprot.writeFieldEnd()
    if self.cur_idepth != None:
      oprot.writeFieldBegin('cur_idepth', TType.I32, 6)
      oprot.writeI32(self.cur_idepth)
      oprot.writeFieldEnd()
    if self.cur_xdepth != None:
      oprot.writeFieldBegin('cur_xdepth', TType.I32, 7)
      oprot.writeI32(self.cur_xdepth)
      oprot.writeFieldEnd()
    if self.priority != None:
      oprot.writeFieldBegin('priority', TType.I32, 8)
      oprot.writeI32(self.priority)
      oprot.writeFieldEnd()
    if self.crawl_interval != None:
      oprot.writeFieldBegin('crawl_interval', TType.I32, 9)
      oprot.writeI32(self.crawl_interval)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()
    def validate(self):
      return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class SeedsPackage:
  """
  Attributes:
   - ID
   - seeds
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'ID', None, None, ), # 1
    (2, TType.LIST, 'seeds', (TType.STRUCT,(Seed, Seed.thrift_spec)), [
    ], ), # 2
  )

  def __init__(self, ID=None, seeds=thrift_spec[2][4],):
    self.ID = ID
    if seeds is self.thrift_spec[2][4]:
      seeds = [
    ]
    self.seeds = seeds

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.ID = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.seeds = []
          (_etype3, _size0) = iprot.readListBegin()
          for _i4 in xrange(_size0):
            _elem5 = Seed()
            _elem5.read(iprot)
            self.seeds.append(_elem5)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('SeedsPackage')
    if self.ID != None:
      oprot.writeFieldBegin('ID', TType.STRING, 1)
      oprot.writeString(self.ID)
      oprot.writeFieldEnd()
    if self.seeds != None:
      oprot.writeFieldBegin('seeds', TType.LIST, 2)
      oprot.writeListBegin(TType.STRUCT, len(self.seeds))
      for iter6 in self.seeds:
        iter6.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()
    def validate(self):
      return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class JobReport:
  """
  Attributes:
   - spiderid
   - work_time
   - idle_time
   - fail_url_num
   - crawled_url_num
   - crawled_page_size
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'spiderid', None, None, ), # 1
    (2, TType.I32, 'work_time', None, 0, ), # 2
    (3, TType.I32, 'idle_time', None, 0, ), # 3
    (4, TType.I32, 'fail_url_num', None, 0, ), # 4
    (5, TType.I32, 'crawled_url_num', None, 0, ), # 5
    (6, TType.I32, 'crawled_page_size', None, 0, ), # 6
  )

  def __init__(self, spiderid=None, work_time=thrift_spec[2][4], idle_time=thrift_spec[3][4], fail_url_num=thrift_spec[4][4], crawled_url_num=thrift_spec[5][4], crawled_page_size=thrift_spec[6][4],):
    self.spiderid = spiderid
    self.work_time = work_time
    self.idle_time = idle_time
    self.fail_url_num = fail_url_num
    self.crawled_url_num = crawled_url_num
    self.crawled_page_size = crawled_page_size

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.spiderid = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.work_time = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.idle_time = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.fail_url_num = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.crawled_url_num = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.crawled_page_size = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('JobReport')
    if self.spiderid != None:
      oprot.writeFieldBegin('spiderid', TType.STRING, 1)
      oprot.writeString(self.spiderid)
      oprot.writeFieldEnd()
    if self.work_time != None:
      oprot.writeFieldBegin('work_time', TType.I32, 2)
      oprot.writeI32(self.work_time)
      oprot.writeFieldEnd()
    if self.idle_time != None:
      oprot.writeFieldBegin('idle_time', TType.I32, 3)
      oprot.writeI32(self.idle_time)
      oprot.writeFieldEnd()
    if self.fail_url_num != None:
      oprot.writeFieldBegin('fail_url_num', TType.I32, 4)
      oprot.writeI32(self.fail_url_num)
      oprot.writeFieldEnd()
    if self.crawled_url_num != None:
      oprot.writeFieldBegin('crawled_url_num', TType.I32, 5)
      oprot.writeI32(self.crawled_url_num)
      oprot.writeFieldEnd()
    if self.crawled_page_size != None:
      oprot.writeFieldBegin('crawled_page_size', TType.I32, 6)
      oprot.writeI32(self.crawled_page_size)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()
    def validate(self):
      return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class ServerError(Exception):
  """
  Attributes:
   - reason
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'reason', None, "unkown server internal error", ), # 1
  )

  def __init__(self, reason=thrift_spec[1][4],):
    self.reason = reason

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.reason = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('ServerError')
    if self.reason != None:
      oprot.writeFieldBegin('reason', TType.STRING, 1)
      oprot.writeString(self.reason)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()
    def validate(self):
      return


  def __str__(self):
    return repr(self)

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class RequestError(Exception):
  """
  Attributes:
   - reason
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'reason', None, "illeage request", ), # 1
  )

  def __init__(self, reason=thrift_spec[1][4],):
    self.reason = reason

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.reason = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('RequestError')
    if self.reason != None:
      oprot.writeFieldBegin('reason', TType.STRING, 1)
      oprot.writeString(self.reason)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()
    def validate(self):
      return


  def __str__(self):
    return repr(self)

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
